### ISSUE TITLE
请教 两个问题：

### ISSUE THREAD

**Issue by wilson9x1** [ysrc/F-Scrack#3]
项目代码很棒，点赞！
+++++++++++++++++++
请教 两个问题：
1.类似于这种的二进制字符串你是怎么发现并构造的呢？抓包么？
<img width="634" alt="c7a5f0c4-aee0-4083-b28c-733186df800e" src="https://cloud.githubusercontent.com/assets/9835472/20258697/d136ea30-aa8b-11e6-9a2d-cfc06ccd34d5.png">
2.mssql这边sock.connect的port参数应该转一下int吧？我改了本地测试mssql，并不能成功登入。
<img width="537" alt="afab9c4b-71c5-44b9-8250-18e228d4e656" src="https://cloud.githubusercontent.com/assets/9835472/20258734/fd0d0b80-aa8b-11e6-8145-9de9eb227cd7.png">

**Comment by ywolf** [comment]
1.通过wireshark抓取认证包分析构造。
2.确实忘加了，已经修复更新上去。

**Comment by coffeehb** [comment]
有2个问题想问下：
        1、有没有必要抓取退出登录的协议包在脚本里实现，因为我之前用socket模拟ftp，mysql 实现登录时，发现登录后，如果放任不管了这个登录连接一直保持。
        2、你代码里面socket似乎都没有close关闭，哪问题来了：是直接客户端socket close掉好呢，还是模拟服务正常登出好呢？？

最后，还是挺赞的，我喜欢用这种socket伪装一切服务的思路。
