### ISSUE TITLE
有2个问题想问下：

### ISSUE THREAD

**Issue by coffeehb** [ysrc/F-Scrack#4]
hi  ywolf：
1、有没有必要抓取退出登录的协议包在脚本里实现，因为我之前用socket模拟ftp，mysql 实现登录时，发现登录后，如果放任不管了这个登录连接一直保持。
2、你代码里面socket似乎都没有close关闭，哪问题来了：是直接客户端socket close掉好呢，还是模拟服务正常登出好呢？？

最后，还是挺赞的，我喜欢用这种socket伪装一切服务的思路。

**Comment by ywolf** [comment]
1、不嫌麻烦也可以做，但感觉没必要，让他自己超时就好了。
2、多谢提醒，居然忘记close了，等下就更新上去。
